baseurl = "https://stevenmurschel.com/"
title = "Steven Murschel"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "Red"
  description = "Home for a scientist. Codename: Steven."
  copyright = "&copy;2019 Steven Murschel"
  sidebarAbout = [
    "Environmental scientist specializing in applying GIS data analysis to the field(s) of urban, wetland, and riparian ecology, natural resources, and climate adaptation/resilience so our communities can work collaboratively with ecosystems.",
    "Originally from Lake Erie, currently based in Portland, Oregon."
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "stevenmurschel@gmail.com"

    # Optional Matomo analytics (formerly piwik)
      # [params.analytics.matomo]
      #  URL = "https://stats.example.com"
      #  ID = "42"
      #  # Track all subdomains with "*.example.com" (Optional)
      #  domain = "www.example.com"
      #  # Optional integrity check hash
      #  hash = ""

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [params.social]
  facebook      = "https://www.facebook.com/profile.php?id=100017010018324"
  googleplus    = "https://mashable.com/2017/01/18/who-is-using-google-plus-anyway/"
  email         = "stevenmurschel@gmail.com"
  twitter       = "https://twitter.com/bvrambssdrs?lang=en"
  linkedin      = "https://www.linkedin.com/in/steven-murschel-589382a5"
  stackoverflow = "https://stackoverflow.com/users/11867124/estebangatillo"
  instagram     = "https://www.instagram.com/remyofalltrades/?hl=en"
  github        = "https://github.com/wesbos/dad-jokes"
  youtube       = "https://www.youtube.com/watch?v=7MkHpWN-otQ"
  
